# web
spring:
  mvc:
    # 过滤规则
    static-path-pattern: /**
  resources:
    # 静态资源位置
    static-locations: classpath:/static/
  # Freemarker
  freemarker:
    #HttpServletRequest 的属性是否可以覆盖 controller 中 model 的同名项
    allow-request-override: false
    #HttpServletSession 的属性是否可以覆盖 controller 中 model 的同名项
    allow-session-override: false
    # 是否开启缓存
    cache: false
    # 模板文件编码
    charset: UTF-8
    # 是否检查模板位置
    check-template-location: true
    # Content-Type 的值
    content-type: text/html
    # 是否将 HttpServletRequest 中的属性添加 Model 中
    expose-request-attributes: false
    # 是否将 HttpServletRequest 中的属性添加 Model 中
    expose-session-attributes: false
    # 模板文件后缀
    suffix: .ftl
    # 模板文件位置
    template-loader-path: classpath:/templates/


# Tomcat
server:
  port: 8050


